{% set name = "inquirer" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inquirer-{{ version }}.tar.gz
  sha256: 8edc99c076386ee2d2204e5e3653c2488244e82cb197b2d498b3c1b5ffb25d0b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - setuptools
  run:
    - blessed >=1.19.0
    - python >={{ python_min }}
    - readchar >=4.2.0
    - editor >=1.6.0

test:
  imports:
    - inquirer
    - inquirer.render
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/magmax/python-inquirer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of common interactive command line user interfaces, based on Inquirer.js

extra:
  recipe-maintainers:
    - mxr-conda
    - nicornk
